### PR TITLE
Add .envrc to set up developer environment

### PR DESCRIPTION
**Pull request by Rovanion**
This is just a small helper thing for developers, but if they have Direnv and Guix installed this file will automatically start a developer environment with all the dependencies of this project when the user enters the directory with their shell. Perhaps the most useful thing is that there now exists an explicit dependency list.

### CODE REVIEW

**Comment by tarwirdur** [comment]
Maybe better to add `requirements.txt`? It is more general than Guix.

**Comment by tarwirdur** [comment]
I don't see `python-sqlite3` in your `.envrc`.
And I don't see it at all in the repository: https://guix.gnu.org/packages/P/page/24/ (There is no search? Seriously? ;) )

**Comment by Rovanion** [comment]
That is because the sqlite3 library is a part of Python itself: https://docs.python.org/3/library/sqlite3.html

```
$ guix environment --pure --ad-hoc python -- python3
Python 3.8.2 (default, Jan  1 1970, 00:00:01) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> con = sqlite3.connect('example.db')
```

But yeah, it's bad that they haven't gotten around to making a package search as part of their website. I can guarantee you there's been opponents to both making a server based and JavaScript-based search so noone's been motivated enough to make either of them. Until then I get by using `guix search`.

> Maybe better to add requirements.txt? It is more general than Guix.

I guess that depends on which values you put in the word general. Guix is more general in the sense that it not only provides the python libraries but also the virtual environment and python itself. A requirements.txt-file requires the user to bring their own installation of pip, Python and virtualenv through some other package manager.

**Comment by tarwirdur** [comment]
> Guix is more general in the sense that it not only provides the python libraries but also the virtual environment and python itself

In my opinion, this is a narrowly distributive-oriented solution. 
A more general solution would be to use `Dockerfile` for the virtual environment but this is a bit ridiculous for such a small project. 

There are many implementations of the virtual environment. Part exclusively for python (`virtualenv`, `enviroment.yml` from `conda`), part for the entire system (`guix`, `docker`).

It would be ugly to add a config file for each virtual-env system to the repository. I also assume that guix is less popular than any of the other systems listed above.

> A requirements.txt-file requires the user to bring their own installation of pip

I usually don't use pip, preferring the OS package manager for python libraries. I open the file to see the list of dependencies and install them manually. 

___

**However**, if you still think that this is useful, I am ready to accept pull request if you add also `requirements.txt` to it and add description to the `README.md`.


> sqlite3 library is a part of Python itself

Ooops. Really. Sorry.

**Comment by Rovanion** [comment]
> In my opinion, this is a narrowly distributive-oriented solution.

I'm not sure I understand.

> A more general solution would be to use Dockerfile for the virtual environment but this is a bit ridiculous for such a small project.

If you want to create a container around the shell/environment created by `guix environment` you can add a `--container` to the function call. This would create the same situation as you would end up with if you had written a `Dockerfile` and then ran `docker build` followed by `docker run`, IIRC.

But Guix is absolutely less popular than `pip` or `conda`, no doubt about it. I will close this PR since I just wanted to contribute what I had to do in order to get it working.

Either way: Thank you for your wonderful little script. You are helping me and my three friends stay alive right now because you allowed me to create an overlay of an avalanche risk map on top of OsmAnd where I have the mountaineering trips we are considering planned out. And during our trip today we were able to stay clear of avalanche risk zones as we were skiing back down. So <3

**Comment by tarwirdur** [comment]
> I'm not sure I understand.

Unfortunately, I don't think I am speaking correctly in English. 
I meant that currently `guix` works only in a small number of distributions.

> Thank you for your wonderful little script.

I am glad. I didn't expect the script to be so popular.

**Comment by Rovanion** [comment]
> Unfortunately, I don't think I am speaking correctly in English.
> I meant that currently guix works only in a small number of distributions.

No worries :)

Guix should work on any Linux distribution, it's a self contained package manager. It works in isolation from the rest of the system operating in the folder `/gnu/store` as the storage for all packages. The user needs root access in order to create that folder, but if they have that they only need to run `curl -L guix.gnu.org/install.sh | sh`; or a little more responsibly follow the [instructions in the manual](curl -L guix.gnu.org/install.sh). Though I guess I have only tried it on Ubuntu myself, besides my full Guix System install.

**Pull request closed without merging**
